[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "video2image"
version = "1.4.0"
description = "A Python script to extract frames from video files with advanced features."
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Sakthivel J", email = "sakthivel1023@gmail.com"}
]
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Multimedia :: Video",
]
dependencies = [
    "opencv-python",
    "tqdm",
    "pyyaml",
    "numpy",
]

[project.urls]
Homepage = "https://github.com/sakthivelj/video2image"
Repository = "https://github.com/sakthivelj/video2image"
Issues = "https://github.com/sakthivelj/video2image/issues"

[project.scripts]
video2image = "video2image.__init__:main"

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
skip = ["tests/test_converter.py"]
